"""
Django settings for gfdash project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
###################################################################
#dockerを使わずローカル環境で実行する場合は、
# .envファイルを読み込むために以下のコメントを外して下さい
# requirements.txtの修正を忘れた場合は、個別インストールを実行して下さい
# pip install python-dotenv
###################################################################
#from dotenv import load_dotenv
#load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-insecure-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gfdash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gfdash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB', 'hogehoge_db'),
        'USER': os.environ.get('POSTGRES_USER', 'admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c search_path=gf'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# collectstatic の出力先。未設定だと collectstatic が ImproperlyConfigured で
# 失敗し、DEBUG=False 時に静的ファイルが配信されなくなる。
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'  # ログイン成功時はダッシュボード(index.htmlルート)へ
LOGOUT_REDIRECT_URL = 'login'

# サンプル公開モードの設定
# True: ログイン不要で全画面閲覧可能 / False: 通常のログイン必須モード
# ** インターネット上でTrueとする場合、誰でも見れる状態となるので注意すること **
IS_SAMPLE_MODE = False

# ==========================================
# LLM (Ollama) / Batch Execution Settings
# ==========================================
# OllamaのAPIエンドポイント (Dockerのネットワーク構成に合わせて .env で上書き可能)
OLLAMA_API_URL = os.environ.get('OLLAMA_API_URL', 'http://host.docker.internal:11434/api/generate')

# 使用するLLMモデル名 (デフォルトは qwen2.5:7b を想定)
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'gemma4:e4b')

# 独自の追加プロンプトを格納するディレクトリ (このディレクトリは .gitignore で非公開にする)
LLM_CUSTOM_PROMPT_DIR = os.path.join(BASE_DIR, 'custom_prompts')

OLLAMA_NUM_CTX = 4096                   # LLMが確保する記憶領域(トークン数)のデフォルト
OLLAMA_TIMEOUT = 300                    # APIのタイムアウト秒数（CPU処理などで遅い場合は 600 等に延長）
# Ollama に送るプロンプトをログ出力するか（開発時の調査用）
# .env / docker-compose の環境変数で上書きできます
OLLAMA_LOG_PROMPT = os.environ.get('OLLAMA_LOG_PROMPT', 'False') == 'True'
OLLAMA_ALLOW_MODEL_SELECT = True        # Ollamaが使用するローカルLLMの切り替え機能フラグ(固定したい場合はFalseとしてください)

# AI予測やLLMレポート生成などの重いバッチ処理を無効化するかどうか
# ※OllamaやProphetの環境構築が完了し、実際に機能を使用する際は
#   .env に DISABLE_BATCH_EXECUTION=False を設定してください（コードの書き換えは不要）。
DISABLE_BATCH_EXECUTION = os.environ.get('DISABLE_BATCH_EXECUTION', 'True') == 'True'