"""
Django settings for gfdash project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
###################################################################
#dockerを使わずローカル環境で実行する場合は、
# .envファイルを読み込むために以下のコメントを外して下さい
# requirements.txtの修正を忘れた場合は、個別インストールを実行して下さい
# pip install python-dotenv
###################################################################
#from dotenv import load_dotenv
#load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-insecure-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# カンマ区切りで指定する。例: ALLOWED_HOSTS=example.com,192.168.0.10
# 既定は '*'(従来どおり)。インターネットに公開する場合は必ず絞ること。
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()]

# CSRF を通すオリジン。スキーム込みで指定する。
# 例: CSRF_TRUSTED_ORIGINS=https://example.com,http://192.168.0.10:8000
# 未設定なら空(従来どおり)。データ更新画面が 403 になる場合はここを設定する。
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gfdash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gfdash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB', 'hogehoge_db'),
        'USER': os.environ.get('POSTGRES_USER', 'admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c search_path=gf'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# collectstatic の出力先。未設定だと collectstatic が ImproperlyConfigured で
# 失敗し、DEBUG=False 時に静的ファイルが配信されなくなる。
# STATIC_ROOT=/var/www/gfdash/static のように、環境変数で配信先を指定できる。
# nginx などが別の場所を見ている本番環境で使う。未設定なら BASE_DIR/staticfiles。
STATIC_ROOT = os.environ.get('STATIC_ROOT') or (BASE_DIR / 'staticfiles')

# 静的ファイルの配信方式。whitenoise が gzip / brotli 版を生成して配信する。
# ファイル名にハッシュを付けたい場合は環境変数で
#   STATICFILES_BACKEND=whitenoise.storage.CompressedManifestStaticFilesStorage
# を指定する。ただし CSS 内の参照が1つでも解決できないと collectstatic が失敗する。
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': os.environ.get(
            'STATICFILES_BACKEND',
            'whitenoise.storage.CompressedStaticFilesStorage',
        ),
    },
}

MEDIA_ROOT = os.environ.get('MEDIA_ROOT') or os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'  # ログイン成功時はダッシュボード(index.htmlルート)へ
LOGOUT_REDIRECT_URL = 'login'

# サンプル公開モードの設定
# True: ログイン不要で全画面閲覧可能 / False: 通常のログイン必須モード
# ** インターネット上でTrueとする場合、誰でも見れる状態となるので注意すること **
IS_SAMPLE_MODE = os.environ.get('IS_SAMPLE_MODE', 'False') == 'True'

# ==========================================
# LLM (Ollama) / Batch Execution Settings
# ==========================================
# OllamaのAPIエンドポイント (Dockerのネットワーク構成に合わせて .env で上書き可能)
OLLAMA_API_URL = os.environ.get('OLLAMA_API_URL', 'http://host.docker.internal:11434/api/generate')

# 使用するLLMモデル名 (デフォルトは qwen2.5:7b を想定)
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'gemma4:e4b')

# 独自の追加プロンプトを格納するディレクトリ (このディレクトリは .gitignore で非公開にする)
LLM_CUSTOM_PROMPT_DIR = os.path.join(BASE_DIR, 'custom_prompts')

OLLAMA_NUM_CTX = 4096                   # LLMが確保する記憶領域(トークン数)のデフォルト
OLLAMA_TIMEOUT = 300                    # APIのタイムアウト秒数（CPU処理などで遅い場合は 600 等に延長）
# Ollama に送るプロンプトをログ出力するか（開発時の調査用）
# .env / docker-compose の環境変数で上書きできます
OLLAMA_LOG_PROMPT = os.environ.get('OLLAMA_LOG_PROMPT', 'False') == 'True'
OLLAMA_ALLOW_MODEL_SELECT = os.environ.get('OLLAMA_ALLOW_MODEL_SELECT', 'True') == 'True'

# AI予測やLLMレポート生成などの重いバッチ処理を無効化するかどうか
# ※OllamaやProphetの環境構築が完了し、実際に機能を使用する際は
#   .env に DISABLE_BATCH_EXECUTION=False を設定してください（コードの書き換えは不要）。
DISABLE_BATCH_EXECUTION = os.environ.get('DISABLE_BATCH_EXECUTION', 'True') == 'True'

# 休業・祝日カレンダー(913)で過去日を編集できるようにするかどうか。
#
# 既定は True（編集可）です。本システムだけで運用する場合、過去日を
# 編集できないと実績を補完できず不便なためです。
#
# 来場実績を外部システム（Access等）から取り込んでいる場合、過去日は
# そちらが正となり、画面で編集しても取り込みのたびに上書きされます。
# 誤入力を防ぎたい場合は .env に False を設定してください。
ALLOW_PAST_CALENDAR_EDIT = os.environ.get('ALLOW_PAST_CALENDAR_EDIT', 'True') == 'True'