# Generated by Django 6.0 on 2026-08-10 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ta215Attnd',
            fields=[
                ('business_day', models.DateField(primary_key=True, serialize=False, verbose_name='営業日')),
                ('early_morn', models.IntegerField(default=0, verbose_name='早朝')),
                ('morning', models.IntegerField(default=0, verbose_name='午前')),
                ('afternoon', models.IntegerField(default=0, verbose_name='日中')),
                ('night', models.IntegerField(default=0, verbose_name='夜間')),
                ('late_night', models.IntegerField(default=0, verbose_name='深夜')),
                ('member', models.IntegerField(default=0, verbose_name='会員')),
                ('visitor', models.IntegerField(default=0, verbose_name='ビジター')),
                ('int_school', models.IntegerField(default=0, verbose_name='内部スクール')),
                ('ext_school', models.IntegerField(default=0, verbose_name='外部スクール')),
                ('school_total', models.IntegerField(default=0, verbose_name='スクール合計')),
            ],
            options={
                'verbose_name': '来場統計メイン',
                'db_table': 'ta215_attnd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ta216AttndAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_day', models.DateField(verbose_name='営業日')),
                ('attr_name', models.CharField(max_length=50, verbose_name='属性名')),
                ('val', models.IntegerField(default=0, verbose_name='数値')),
            ],
            options={
                'verbose_name': '拡張来場属性',
                'db_table': 'ta216_attnd_attr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ta220Memo',
            fields=[
                ('business_day', models.DateField(primary_key=True, serialize=False, verbose_name='営業日')),
                ('holiday_flg', models.BooleanField(default=False, verbose_name='祝日フラグ')),
                ('tokubetu_flg', models.BooleanField(default=False, verbose_name='特別営業フラグ')),
                ('closed_flg', models.BooleanField(default=False, verbose_name='休業フラグ')),
                ('temp_closed', models.IntegerField(default=0, verbose_name='時間休業フラグ')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='入力日')),
            ],
            options={
                'verbose_name': '日次備考情報',
                'db_table': 'ta220_memo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tb120Report',
            fields=[
                ('business_day', models.DateField(primary_key=True, serialize=False)),
                ('aridaka', models.IntegerField(blank=True, null=True)),
                ('nyukin', models.IntegerField(blank=True, null=True)),
                ('shukkin', models.IntegerField(blank=True, null=True)),
                ('sagaku', models.IntegerField(blank=True, null=True)),
                ('ken', models.IntegerField(blank=True, null=True)),
                ('school', models.IntegerField(blank=True, null=True)),
                ('shop', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb120_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tb330SalesDiff',
            fields=[
                ('diff_date', models.DateField(primary_key=True, serialize=False)),
                ('diff_sales', models.IntegerField(blank=True, null=True)),
                ('diff_time_flg', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb330_sales_diff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz101WeatherReport',
            fields=[
                ('weather_day', models.DateField(primary_key=True, serialize=False, verbose_name='日付')),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最高気温')),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最低気温')),
                ('temp_ave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='平均気温')),
                ('rainfall_hour_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='降水量（１０分間最大）')),
                ('wind_max_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='日最風速')),
                ('wind_max_direction', models.CharField(max_length=255, null=True)),
                ('wind_max_inst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='日最大瞬間風速')),
                ('wind_max_inst_dir', models.CharField(max_length=255, null=True)),
                ('gaikyo', models.CharField(max_length=255, null=True)),
                ('gaikyo_night', models.CharField(max_length=255, null=True)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録・更新日時')),
            ],
            options={
                'verbose_name': '気象データ',
                'verbose_name_plural': '気象データ',
                'db_table': 'tz101_weather_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz102WeatherAvarage',
            fields=[
                ('weather_mmdd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('weather_mm', models.IntegerField()),
                ('weather_dd', models.IntegerField()),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最高気温')),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最低気温')),
                ('temp_ave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='平均気温')),
            ],
            options={
                'db_table': 'tz102_weather_avarage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz105DetailedWeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_day', models.DateField(verbose_name='年月日')),
                ('weather_time', models.IntegerField(verbose_name='時')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_direction', models.CharField(max_length=255, null=True)),
                ('weather_num', models.IntegerField(null=True)),
                ('input_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gf"."tz105_detailed_weather_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz201DeptReport',
            fields=[
                ('business_day', models.DateField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tz201_dept_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz202ClerkReport',
            fields=[
                ('business_day', models.DateField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('trans_num', models.IntegerField(blank=True, null=True)),
                ('sales_num', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tz202_clerk_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz301AttendanceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_day', models.DateField(verbose_name='予測対象日')),
                ('target_cls', models.CharField(max_length=255, verbose_name='予測対象区分')),
                ('yhat', models.FloatField(verbose_name='予測値')),
                ('yhat_lower', models.FloatField(verbose_name='予測下限値')),
                ('yhat_upper', models.FloatField(verbose_name='予測上限値')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='データ入力日')),
            ],
            options={
                'verbose_name': '来場者予測情報',
                'verbose_name_plural': '来場者予測情報',
                'db_table': 'tz301_forecast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz302LlmAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('report_cls', models.CharField(max_length=20, verbose_name='レポート区分')),
                ('report_text', models.TextField(verbose_name='AI分析レポート')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='データ入力日')),
            ],
            options={
                'verbose_name': 'AI月次分析レポート',
                'verbose_name_plural': 'AI月次分析レポート',
                'db_table': 'tz302_llm_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz901ComName',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tz901_com_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz910Permission',
            fields=[
                ('template_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('required_level', models.IntegerField(default=0)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tz910_permission',
                'managed': False,
            },
        ),
    ]
