# Generated by Django 6.0 on 2026-08-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tz103WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prec_no', models.CharField(max_length=4, verbose_name='都府県・地方コード')),
                ('block_no', models.CharField(max_length=8, verbose_name='観測地点コード')),
                ('station_type', models.CharField(max_length=1, verbose_name='地点種別')),
                ('prec_name', models.CharField(max_length=50, verbose_name='都府県・地方名')),
                ('station_name', models.CharField(max_length=50, verbose_name='観測地点名')),
                ('has_rainfall', models.BooleanField(default=False, verbose_name='降水量観測')),
                ('has_wind', models.BooleanField(default=False, verbose_name='風速観測')),
                ('has_temp', models.BooleanField(default=False, verbose_name='気温観測')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='観測終了日')),
            ],
            options={
                'db_table': 'tz103_weather_station',
                'managed': False,
            },
        ),
    ]
