# Generated by Django 6.0 on 2026-09-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_permission_config_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tz810Holiday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_cls', models.IntegerField(verbose_name='カレンダー種別')),
                ('business_day', models.DateField(verbose_name='対象日')),
                ('day_cls', models.SmallIntegerField(choices=[(1, '休日'), (2, '稼働日')], default=1, verbose_name='日区分')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='入力日')),
            ],
            options={
                'verbose_name': '第2休日カレンダー',
                'verbose_name_plural': '第2休日カレンダー',
                'db_table': 'tz810_holiday2',
                'managed': False,
            },
        ),
    ]
