# Generated by Django 6.0 on 2026-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_attendance_upload_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tz310AiRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False, verbose_name='実行ID')),
                ('run_kind', models.CharField(max_length=20, verbose_name='実行区分')),
                ('executed_at', models.DateTimeField(verbose_name='実行日時')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='状態')),
                ('script_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='スクリプト版')),
                ('prompt_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='プロンプト版')),
                ('history_from', models.DateField(blank=True, null=True, verbose_name='履歴保存の下限日')),
                ('periods', models.IntegerField(blank=True, null=True, verbose_name='予測日数')),
                ('holiday2_enabled', models.BooleanField(blank=True, null=True, verbose_name='第2休日の利用')),
                ('closure_sample_count', models.IntegerField(blank=True, null=True, verbose_name='休業補正の実績日数')),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='LLMモデル')),
                ('llm_preset', models.CharField(blank=True, max_length=20, null=True, verbose_name='実行プリセット')),
                ('applied_remark_json', models.TextField(blank=True, null=True, verbose_name='採用した所見')),
                ('note', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': 'AIバッチ実行ヘッダ',
                'verbose_name_plural': 'AIバッチ実行ヘッダ',
                'db_table': 'tz310_ai_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz311ForecastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField(verbose_name='実行ID')),
                ('business_day', models.DateField(verbose_name='予測対象日')),
                ('target_cls', models.CharField(max_length=255, verbose_name='予測対象区分')),
                ('yhat', models.FloatField(verbose_name='予測値')),
                ('yhat_lower', models.FloatField(verbose_name='予測下限値')),
                ('yhat_upper', models.FloatField(verbose_name='予測上限値')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='データ入力日')),
            ],
            options={
                'verbose_name': '来場者予測履歴',
                'verbose_name_plural': '来場者予測履歴',
                'db_table': 'tz311_forecast_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tz312ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField(verbose_name='実行ID')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('report_cls', models.CharField(max_length=20, verbose_name='レポート区分')),
                ('report_text', models.TextField(verbose_name='AI分析レポート')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='データ入力日')),
            ],
            options={
                'verbose_name': 'AI月次分析レポート履歴',
                'verbose_name_plural': 'AI月次分析レポート履歴',
                'db_table': 'tz312_report_history',
                'managed': False,
            },
        ),
    ]
