# Generated by Django 6.0 on 2026-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_forecast_compare_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tz305MonthlyRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('remark_cls', models.CharField(max_length=20, verbose_name='所見区分')),
                ('remark_text', models.TextField(default='', verbose_name='所見')),
                ('parsed_json', models.TextField(blank=True, null=True, verbose_name='解析結果')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析日時')),
                ('parsed_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='解析モデル')),
                ('parse_status', models.CharField(default='none', max_length=20, verbose_name='解析状態')),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '月次所見',
                'verbose_name_plural': '月次所見',
                'db_table': 'tz305_monthly_remark',
                'managed': False,
            },
        ),
    ]
