# Generated by Django 6.0 on 2026-09-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_remark_maintenance_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tz391LlmCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='プロバイダ')),
                ('endpoint', models.CharField(max_length=200, verbose_name='接続先')),
                ('model_name', models.CharField(max_length=200, verbose_name='モデル名')),
                ('model_digest', models.CharField(blank=True, default='', max_length=80, verbose_name='ダイジェスト')),
                ('think_supported', models.BooleanField(default=False, verbose_name='thinkingの可否')),
                ('effort_status', models.CharField(default='unknown', max_length=20, verbose_name='強さの状態')),
                ('effort_values', models.JSONField(default=list, verbose_name='acceptedな強さ')),
                ('probe_note', models.TextField(blank=True, default='', verbose_name='判定の根拠')),
                ('last_engine', models.CharField(blank=True, default='', max_length=20, verbose_name='最後のエンジン')),
                ('last_num_ctx', models.IntegerField(blank=True, null=True, verbose_name='最後のコンテキスト長')),
                ('last_timeout', models.IntegerField(blank=True, null=True, verbose_name='最後のタイムアウト')),
                ('last_think', models.BooleanField(blank=True, null=True, verbose_name='最後のthinking')),
                ('last_effort', models.CharField(blank=True, default='', max_length=10, verbose_name='最後の強さ')),
                ('measured_at', models.DateTimeField(blank=True, null=True, verbose_name='測定日時')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='データ入力日')),
            ],
            options={
                'verbose_name': '推論エンジン能力',
                'verbose_name_plural': '推論エンジン能力',
                'db_table': 'tz391_llm_capability',
                'managed': False,
            },
        ),
    ]
